---
sidebar: sidebar 
permalink: codebox-automation.html 
keywords: codebox, automation 
summary: 'Codebox est un copilote d"infrastructure en tant que code (IaC) qui aide les développeurs et DevOps à générer le code nécessaire pour exécuter toute opération prise en charge par NetApp Workload Factory.' 
---
= En savoir plus sur l'automatisation de la boîte de code
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Codebox est un copilote d'infrastructure en tant que code (IaC) qui aide les développeurs et DevOps à générer le code nécessaire pour exécuter toute opération prise en charge par NetApp Workload Factory.  Codebox est aligné sur les modes de fonctionnement de Workload Factory (_basic_, _read-only_ et _read/write_) et définit un chemin clair pour la préparation à l'exécution tout en fournissant un catalogue d'automatisation pour une réutilisation future rapide.



== Fonctions de la Codebox

Codebox offre deux fonctionnalités IAC clés :

* _Codebox Viewer_ affiche l'IAC généré par une opération de flux de travaux spécifique en faisant correspondre les entrées et les sélections de l'assistant graphique ou de l'interface de conversation. Même si Codebox Viewer prend en charge le codage couleur pour faciliter la navigation et l'analyse, il ne permet pas la modification, mais uniquement la copie ou l'enregistrement du code dans le catalogue d'automatisation.
* _Codebox Automation Catalog_ affiche tous les travaux IAC enregistrés, ce qui vous permet de les référencer facilement pour une utilisation ultérieure. Les travaux du catalogue d'automatisation sont enregistrés en tant que modèles et affichés dans le contexte des ressources qui s'y appliquent.


De plus, lors de la configuration des informations d’identification de Workload Factory, Codebox affiche dynamiquement les autorisations AWS nécessaires pour créer des stratégies IAM.  Les autorisations sont fournies pour chaque fonctionnalité Workload Factory que vous prévoyez d'utiliser (bases de données, IA, FSx pour ONTAP, etc.), et elles sont personnalisées selon que les utilisateurs de la politique obtiendront des autorisations en lecture seule ou des autorisations complètes en lecture/écriture.  Il vous suffit de copier les autorisations de Codebox, puis de les coller dans la console de gestion AWS afin que Workload Factory dispose des autorisations appropriées pour gérer vos charges de travail.



== Formats de code pris en charge

Les formats de code pris en charge sont les suivants :

* API REST de Workload Factory
* CLI AWS
* AWS CloudFormation
* Terraform




== Informations connexes

link:use-codebox.html["Découvrez comment utiliser Codebox"].

link:https://console.workloads.netapp.com/api-doc["Documentation de l'API REST de Workload Factory"^] .
