---
sidebar: sidebar 
permalink: configure-notifications.html 
keywords: amazon, sns, notification, topic, notifications, notifications service, alerts 
summary: 'Vous pouvez configurer la fabrique de charges de travail BlueXP pour envoyer des notifications à une personne ou à une autre application lorsque certains types d"événements se produisent.' 
---
= Configurer les notifications de l'usine de charge de travail BlueXP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Vous pouvez configurer le service de notification de la fabrique de charges de travail BlueXP pour envoyer des notifications au service d'alertes BlueXP ou à une rubrique Amazon SNS. Les notifications envoyées aux alertes BlueXP apparaissent dans le panneau des alertes BlueXP. Lorsque la fabrique de charges de travail publie des notifications dans une rubrique Amazon SNS, les abonnés à cette rubrique (tels que les personnes ou d'autres applications) reçoivent les notifications aux points de terminaison configurés pour cette rubrique (tels que les e-mails ou les SMS).



== Types de notifications et messages

Workload Factory envoie des notifications pour les événements suivants :

[cols="6*"]
|===
| Événement | Description | Type de notification | Gravité | Charge de travail | Type de ressource 


| Certaines instances de base de données de votre compte ne sont pas bien architecturées | Toutes les instances Microsoft SQL Server de votre compte ont été analysées pour détecter les problèmes d'architecture. La description de cet événement indique le nombre d'instances bien architecturées et non optimisées. Consultez les résultats et recommandations concernant l'état d'architecture dans l'inventaire des bases de données de la console Workload Factory. | Bien architecturé | Recommandation | Les bases de données | Instance Microsoft SQL Server 


| Déploiement réussi du serveur Microsoft SQL Server/PostgreSQL | Le déploiement de l'hôte Microsoft SQL Server ou PostgreSQL a réussi. Pour plus d'informations, consultez la section « Surveillance des tâches ». | Déploiement | Réussite | Les bases de données | FSx pour ONTAP, hôte de base de données 


| Échec du déploiement du serveur Microsoft SQL Server/PostgreSQL | Le déploiement de l'hôte Microsoft SQL Server ou PostgreSQL a échoué. Pour plus d'informations, consultez la section Surveillance des tâches. | Déploiement | Erreur | Les bases de données | FSx pour ONTAP, hôte de base de données 
|===


== Configurer les notifications de la fabrique de charges de travail

Configurez les notifications de Workload Factory à l'aide de la console BlueXP ou de la console Workload Factory. Si vous utilisez la console BlueXP, vous pouvez configurer Workload Factory pour envoyer des notifications aux alertes BlueXP ou à une rubrique Amazon SNS. Vous pouvez configurer les alertes BlueXP depuis la section « Paramètres d'alertes et de notifications » de BlueXP.

.Avant de commencer
* Vous devez configurer Amazon SNS et créer des rubriques Amazon SNS à l’aide de la console Amazon SNS ou de l’AWS CLI.
* Notez que Workload Factory prend en charge le type de sujet « Standard ». Ce type de sujet ne garantit pas que les notifications sont envoyées aux abonnés dans l'ordre de réception. Pensez-y donc si vous avez des notifications critiques ou urgentes.


[role="tabbed-block"]
====
.Configurer les notifications depuis la console BlueXP
--
.Étapes
. Connectez-vous au link:https://console.bluexp.netapp.com["Console BlueXP"^].
. Sélectionnez *workloads* dans le menu de navigation de gauche.
. Sélectionnez *Home* pour afficher toutes les charges de travail ou sélectionnez une charge de travail comme *Storage* ou *Databases*.
. Dans la barre de menus de l’usine de charge de travail, sélectionnez le menu de configuration.
. Dans le menu, sélectionnez *Configuration des notifications Workload Factory*.
. Facultatif : sélectionnez *Activer les notifications BlueXP* pour configurer la fabrique de charges de travail afin d’envoyer des notifications aux alertes BlueXP.
. Sélectionnez *Activer les notifications SNS*.
. Suivez les instructions pour configurer Amazon SNS à partir de la console Amazon SNS.
+
Après avoir créé le sujet, copiez l'ARN du sujet et saisissez-le dans le champ *ARN du sujet SNS* dans la boîte de dialogue *Configuration des notifications*.

. Après avoir vérifié la configuration en envoyant une notification de test, sélectionnez *Appliquer*.


.Résultat
Workload Factory est configuré pour envoyer des notifications à la rubrique Amazon SNS que vous avez spécifiée.

--
.Configurer les notifications depuis la console de l'usine de charge de travail
--
.Étapes
. Connectez-vous au link:https://console.workloads.netapp.com["console d'usine de charge de travail"^].
. Ouvrez le menu du compte à partir de la barre de navigation supérieure.
. Dans le menu, sélectionnez *Configuration des notifications*.
. Sélectionnez *Activer les notifications SNS*.
. Suivez les instructions pour configurer Amazon SNS à partir de la console Amazon SNS.
. Après avoir vérifié la configuration en envoyant une notification de test, sélectionnez *Appliquer*.


.Résultat
Workload Factory est configuré pour envoyer des notifications à la rubrique Amazon SNS que vous avez spécifiée.

--
====


== Abonnez-vous au sujet Amazon SNS

Après avoir configuré la fabrique de charges de travail pour envoyer des notifications à un sujet, suivez les instructions  https://docs.aws.amazon.com/sns/latest/dg/sns-create-subscribe-endpoint-to-topic.html["instructions"] dans la documentation Amazon SNS pour vous abonner à la rubrique afin de pouvoir recevoir des notifications de Workload Factory.



== Filtrer les notifications

Vous pouvez réduire le trafic de notifications inutiles et cibler des types de notifications spécifiques pour des utilisateurs spécifiques en appliquant des filtres aux notifications. Pour ce faire, utilisez une politique Amazon SNS pour les notifications SNS et les paramètres de notifications BlueXP.



=== Filtrer les notifications Amazon SNS

Lorsque vous vous abonnez à une rubrique Amazon SNS, vous recevez par défaut toutes les notifications publiées sur cette rubrique. Si vous souhaitez recevoir uniquement des notifications spécifiques de cette rubrique, vous pouvez utiliser une stratégie de filtrage pour contrôler les notifications que vous recevez.

Pour plus d'informations sur la création de politiques de filtrage, reportez-vous à la  https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html["Documentation Amazon SNS"^] .

Pour des exemples de politiques de filtrage, reportez-vous à  https://docs.aws.amazon.com/sns/latest/dg/example-filter-policies.html["Exemples de politiques de filtrage Amazon SNS"^] .



=== Filtrer les notifications BlueXP

Vous pouvez utiliser les paramètres d'alertes et de notifications BlueXP pour filtrer les alertes et les notifications que vous recevez dans BlueXP par niveau de gravité, tel que Critique, Info ou Avertissement.

Pour plus d'informations sur le filtrage des notifications dans BlueXP, reportez-vous à la  https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#filter-notifications["Documentation BlueXP"^] .
