---
sidebar: sidebar 
permalink: configure-notifications.html 
keywords: amazon, sns, notification, topic, notifications, notifications service, alerts, email, email notifications, console notifications, filter, filtering 
summary: 'Vous pouvez configurer NetApp Workload Factory pour envoyer des notifications à une personne ou à une autre application lorsque certains types d"événements se produisent.' 
---
= Configurer les notifications NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Vous pouvez configurer le service de notification NetApp Workload Factory pour envoyer des notifications sous forme d’alertes dans NetApp Console, à toutes les adresses e-mail associées au compte, ou à une rubrique Amazon SNS. Les notifications envoyées sous forme d’alertes s’affichent dans NetApp Console lorsqu’un agent ou un lien Console est déployé. Lorsque Workload Factory publie des notifications sur une rubrique Amazon SNS, les abonnés à cette rubrique (personnes ou autres applications) reçoivent les notifications aux points de terminaison configurés pour la rubrique (par exemple, e-mail ou messages SMS).



== Types de notifications et messages

Workload Factory envoie des notifications pour les événements suivants :

[cols="6*"]
|===
| Événement | Description | Type de notification | Gravité | Charge de travail | Type de ressource 


| Certaines instances de base de données de votre compte ne sont pas bien architecturées | Toutes les instances Microsoft SQL Server de votre compte ont été analysées pour détecter les problèmes bien architecturés.  La description de cet événement donne le nombre d'instances bien architecturées et d'instances non optimisées.  Consultez les résultats et recommandations d’état bien architecturés dans l’inventaire des bases de données à partir de la console Workload Factory. | Bien architecturé | Recommandation | Les bases de données | Instance Microsoft SQL Server 


| Déploiement réussi du serveur Microsoft SQL Server/PostgreSQL | Le déploiement de l'hôte Microsoft SQL Server ou PostgreSQL a réussi. Pour plus d'informations, consultez la section Surveillance des tâches. | Déploiement | Réussite | Les bases de données | FSx pour ONTAP, hôte de base de données 


| Échec du déploiement du serveur Microsoft SQL Server/PostgreSQL | Le déploiement de l'hôte Microsoft SQL Server ou PostgreSQL a échoué. Pour plus d'informations, consultez la section Surveillance des tâches. | Déploiement | Erreur | Les bases de données | FSx pour ONTAP, hôte de base de données 


| Échec de la création de la relation de réplication | La création d’une relation de réplication SnapMirror a échoué.  Pour plus d'informations, rendez-vous sur Tracker. | Réplication | Primordial | Stockage général | FSx pour ONTAP 


| Échec de la création de FSx pour ONTAP | Un processus de création de système de fichiers FSx pour ONTAP a échoué.  Pour plus d'informations, rendez-vous sur Tracker. | Action du système de fichiers FSx pour ONTAP | Primordial | Stockage général | FSx pour ONTAP 


| La capacité automatique des SSD ou des inodes augmente le succès | Lors d'une récente mise à jour de la gestion automatique de la capacité, le système de fichiers FSx pour ONTAP a augmenté avec succès la capacité du SSD ou les inodes de volume. Pour plus d'informations, rendez-vous sur Tracker. | Gestion des capacités | Réussite | Stockage général | Fichier FSx pour ONTAP 


| Échec automatique de l'augmentation de la capacité SSD ou des inodes | Lors d'une récente mise à jour de la gestion automatique de la capacité, le système de fichiers FSx pour ONTAP n'a pas réussi à augmenter la capacité du SSD ou les inodes de volume. Pour plus d'informations, rendez-vous sur Tracker. | Gestion des capacités | Primordial | Stockage général | FSx pour les systèmes de fichiers ONTAP 


| Problème FSx pour ONTAP détecté | Tous les systèmes de fichiers FSx pour ONTAP ont été analysés pour détecter les problèmes bien architecturés.  L'analyse a détecté un ou plusieurs problèmes.  Pour plus d’informations, consultez l’analyse bien architecturée du tableau de bord Stockage dans la console Workload Factory. | Analyse bien architecturée | Recommandation | Stockage général | FSx pour les systèmes de fichiers ONTAP 


| Événement de gestion automatique des capacités pour FSx pour ONTAP | Le niveau de performance SSD pour le système de fichiers FSx pour ONTAP a atteint le seuil d'alerte de capacité/pourcentage total. | Gestion des capacités | Avertissement | Stockage général | FSx pour les systèmes de fichiers ONTAP 


| Événement de gestion automatique des inodes pour FSx pour ONTAP | Le nombre d'inodes du volume FSx pour ONTAP a atteint le seuil d'avertissement (nombre/pourcentage total). | Gestion des capacités | Avertissement | Stockage général | FSx pour les systèmes de fichiers ONTAP 


| Activité suspecte détectée sur le volume FSx for ONTAP système de fichiers | NetApp Autonomous Ransomware Protection avec IA (ARP/IA) a détecté une activité volumique suspecte. | Protection contre les ransomwares | Primordial | Stockage général | FSx pour les systèmes de fichiers ONTAP 


| Dépassement du seuil de latence détecté | Un ou plusieurs volumes dans le cluster FSx for ONTAP ont dépassé le seuil de latence. | Surveillance des performances | Avertissement | EDA | FSx pour les systèmes de fichiers ONTAP 
|===


== Configurer les notifications de Workload Factory

Vous pouvez configurer les notifications de Workload Factory à l'aide de la NetApp Console ou de la console Workload Factory.

Les options pour recevoir des notifications incluent :



=== Console NetApp

* *Notifications* : Configurez Workload Factory pour envoyer des notifications qui apparaissent sous l’icône de cloche dans NetApp Console.
* *Courriel* : Activez les notifications par courriel dans NetApp Console pour recevoir des notifications à toutes les adresses courriel associées au compte sans nécessiter de configuration Amazon SNS.
* *Amazon SNS* : Configurez Workload Factory pour envoyer des notifications à un sujet Amazon SNS.




=== Console Workload Factory

* *Courriel* : Activez les notifications par courriel dans la console Workload Factory pour recevoir des notifications à toutes les adresses courriel associées au compte sans nécessiter de configuration Amazon SNS.
* *Amazon SNS* : Configurez Workload Factory pour envoyer des notifications à un sujet Amazon SNS à l’aide de la console Workload Factory.



IMPORTANT: Lorsque vous configurez les notifications dans NetApp Console, celle-ci prend en charge la distribution des notifications et les options de notification de la console Workload Factory sont désactivées et affichées en mode lecture seule. Une infobulle indique que les notifications sont gérées depuis NetApp Console. Vous pouvez alors gérer les notifications uniquement depuis NetApp Console.

.Avant de commencer
Les conditions préalables suivantes s'appliquent uniquement lors de la configuration des notifications Amazon SNS :

* Vous devez configurer Amazon SNS et créer des rubriques Amazon SNS à l’aide de la console Amazon SNS ou de l’AWS CLI.
* Notez que Workload Factory prend en charge le type de rubrique *Standard*.  Ce type de sujet ne garantit pas que les notifications sont envoyées aux abonnés dans l'ordre dans lequel elles ont été reçues, alors tenez-en compte si vous avez des notifications critiques ou d'urgence.


[role="tabbed-block"]
====
.Configurer les notifications depuis la console NetApp
--
.Étapes
. Connectez-vous à lalink:https://console.netapp.com["Console NetApp"^] .
. Dans le menu de la console NetApp , sélectionnez *Charges de travail*, *Administration*, puis *Configuration des notifications*.
. Sur la page de configuration des notifications, activez un ou plusieurs des types de notifications suivants :
+
.. *NetApp Console notifications* : Sélectionnez *Activer les notifications NetApp Console* pour configurer Workload Factory afin d’envoyer des notifications dans NetApp Console.
.. *Notifications par e-mail* : Sélectionnez *Activer les notifications par e-mail* pour configurer Workload Factory afin qu’il envoie des notifications à toutes les adresses e-mail associées au compte.
.. *Notifications Amazon SNS* : Sélectionnez *Enable SNS notifications*, puis suivez les instructions pour configurer Amazon SNS depuis la console Amazon SNS.
+
Après avoir créé le sujet, copiez l'ARN du sujet et saisissez-le dans le champ *ARN du sujet SNS* sur la page *Configuration des notifications*.



. Après avoir vérifié la configuration en envoyant une notification de test, sélectionnez *Appliquer*.


--
.Configurer les notifications depuis la console Workload Factory
--
.Étapes
. Connectez-vous à lalink:https://console.workloads.netapp.com["Console Workload Factory"^] .
. Dans le menu de la console Workload Factory, sélectionnez *Charges de travail*, *Administration*, puis *Configuration des notifications*.
. Activez un ou plusieurs des types de notification suivants :
+
** *Notifications par e-mail* : Sélectionnez *Activer les notifications par e-mail*. Toutes les adresses e-mail associées au compte sont affichées en mode lecture seule.
** *Notifications Amazon SNS* : Sélectionnez *Enable SNS notifications*, puis suivez les instructions pour configurer Amazon SNS depuis la console Amazon SNS.
+
Après avoir vérifié la configuration en envoyant une notification de test, sélectionnez *Appliquer*.





--
====


== Abonnez-vous au sujet Amazon SNS

Après avoir configuré Workload Factory pour envoyer des notifications à une rubrique, suivez les instructions https://docs.aws.amazon.com/sns/latest/dg/sns-create-subscribe-endpoint-to-topic.html["instructions"] dans la documentation Amazon SNS pour vous abonner à la rubrique afin de pouvoir recevoir des notifications de Workload Factory.



== Filtrer les notifications

Vous pouvez réduire le trafic de notifications inutiles et cibler des types de notifications spécifiques pour des utilisateurs spécifiques en appliquant des filtres aux notifications. Vous pouvez le faire à l'aide d'une stratégie Amazon SNS pour les notifications SNS, et en utilisant les paramètres de notifications dans NetApp Console.



=== Filtrer les notifications Amazon SNS

Lorsque vous vous abonnez à une rubrique Amazon SNS, vous recevez par défaut toutes les notifications publiées sur cette rubrique.  Si vous souhaitez recevoir uniquement des notifications spécifiques du sujet, vous pouvez utiliser une stratégie de filtrage pour contrôler les notifications que vous recevez.  Les politiques de filtrage obligent Amazon SNS à envoyer uniquement les notifications correspondant à la politique de filtrage à l'abonné.

Vous pouvez filtrer les notifications Amazon SNS selon les critères suivants :

[cols="3*"]
|===
| Description | Nom du champ de la politique de filtrage | Valeurs possibles 


| Type de ressource | `resourceType`  a| 
* `DB`
* `Microsoft SQL Server host`
* `PostgreSQL Server host`




| Charge de travail | `workload` | `WLMDB` 


| Priorité | `priority`  a| 
* `Success`
* `Info`
* `Recommendation`
* `Warning`
* `Error`
* `Critical`




| Type de notification | `notificationType`  a| 
* `Deployment`
* `Well-architected`


|===
.Étapes
. Dans la console Amazon SNS, modifiez les détails de l’abonnement pour la rubrique SNS.
. Dans la zone *Politique de filtrage d'abonnement*, sélectionnez le filtrage par *Attributs de message*.
. Activez l'option *Politique de filtrage d'abonnement*.
. Saisissez une politique de filtrage JSON dans la case *Éditeur JSON*.
+
Par exemple, la stratégie de filtrage JSON suivante accepte les notifications de la ressource Microsoft SQL Server qui sont liées à la charge de travail WLMDB, ont une priorité de réussite ou d'erreur et fournissent des détails sur l'état Bien architecturé :

+
[source, json]
----
{
  "accountId": [
    "account-a"
  ],
  "resourceType": [
    "Microsoft SQL Server host"
  ],
  "workload": [
    "WLMDB"
  ],
  "priority": [
    "Success",
    "Error"
  ],
  "notificationType": [
    "Well-architected"
  ]
}
----
. Sélectionnez *Enregistrer les modifications*.


Pour d'autres exemples de politiques de filtrage, reportez-vous à https://docs.aws.amazon.com/sns/latest/dg/example-filter-policies.html["Exemples de politiques de filtrage Amazon SNS"^] .

Pour plus d'informations sur la création de politiques de filtrage, reportez-vous à la https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html["Documentation Amazon SNS"^] .



=== Filtrer les notifications dans la NetApp Console

Vous pouvez utiliser les paramètres de notification de la NetApp Console pour filtrer les notifications que vous recevez dans la Console par niveau de gravité, comme Critique, Info ou Avertissement.

Pour plus d'informations sur le filtrage des notifications dans la console, reportez-vous à la https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html#filter-notifications["Documentation de la console NetApp"^] .
