---
sidebar: sidebar 
permalink: console-experiences.html 
keywords: console, consoles, access, saas, Workload Factory, NetApp Workload Factory, NetApp Console 
summary: NetApp Workload Factory est accessible via deux consoles Web. 
---
= Expériences de la console
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory est accessible via deux consoles Web.  Découvrez comment accéder à Workload Factory à l’aide de la console Workload Factory et de la console NetApp .

* * Console NetApp * : offre une expérience hybride où vous pouvez gérer vos systèmes de fichiers FSx for ONTAP et vos charges de travail exécutées sur Amazon FSx for NetApp ONTAP au même endroit.
* *Console Workload Factory* : offre une expérience Workload Factory dédiée axée sur les charges de travail exécutées sur Amazon FSx for NetApp ONTAP.




== Accéder à Workload Factory dans la console NetApp

Vous pouvez accéder à Workload Factory depuis la NetApp Console. En plus d'utiliser Workload Factory pour les fonctionnalités de stockage et de gestion des charges de travail AWS, vous pouvez également accéder à d'autres services de données tels que NetApp Copy and Sync, et bien plus encore.

.Étapes
. Connectez-vous à lalink:https://console.netapp.com["Console NetApp"^] .
. Dans le menu de la console NetApp , sélectionnez *Charges de travail*, puis *Vue d’ensemble*.




== Accéder à Workload Factory dans la console Workload Factory

Vous pouvez accéder à Workload Factory depuis la console Workload Factory.

.Étape
. Connectez-vous à lalink:https://console.workloads.netapp.com["Console Workload Factory"^] .

