---
sidebar: sidebar 
permalink: manage-credentials.html 
keywords: aws accounts, aws, credentials, edit credentials, manage credentials, delete credentials 
summary: 'Si vous n’avez plus besoin d’un ensemble d’informations d’identification, vous pouvez les supprimer de NetApp Workload Factory.  Vous ne pouvez supprimer que les informations d"identification qui ne sont pas associées à un système de fichiers FSx for ONTAP .' 
---
= Supprimer les informations d'identification de NetApp Workload Factory
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si vous n’avez plus besoin d’un ensemble d’informations d’identification, vous pouvez les supprimer de Workload Factory.  Vous ne pouvez supprimer que les informations d'identification qui ne sont pas associées à un système de fichiers FSx for ONTAP .

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans le menu, sélectionnez *Administration* puis *Informations d'identification*.
. Sur la page *Informations d'identification*, procédez comme suit :
+
** Dans la console Workload Factory, sélectionnez le menu d’action pour un ensemble d’informations d’identification, puis sélectionnez *Supprimer*. Sélectionnez *Supprimer* pour confirmer.
** Dans la console NetApp , sélectionnez le menu d’action pour un ensemble d’informations d’identification, puis sélectionnez *Supprimer*. Sélectionnez *Supprimer* pour confirmer.



