---
settings:
  name: Setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documents de configuration et d'administration
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
  - title: Commencez
    entries:
    - title: Découvrez les bases
      entries:
      - title: Découvrez l'usine de workloads BlueXP 
        url: "/workload-factory-overview.html"
      - title: Modes de fonctionnement
        url: "/operational-modes.html"
      - title: Expériences de la console
        url: "/console-experiences.html"
      - title: Autorisations
        url: "/permissions-reference.html"
    - title: Démarrage rapide
      url: "/quick-start.html"
    - title: Inscrivez-vous à l'usine de workloads
      url: "/sign-up-saas.html"
    - title: Ajoutez des identifiants AWS
      url: "/add-credentials.html"
    - title: Que pouvez-vous faire ensuite
      url: "/whats-next.html"
  - title: Administrer l'usine de la charge de travail
    entries:
    - title: Connectez-vous à l'usine de la charge de travail
      url: "/log-in.html"
    - title: Gestion des comptes de service
      url: "/manage-service-accounts.html"
    - title: Configurez les notifications
      url: "/configure-notifications.html"
    - title: Automatisez les tâches à l'aide de Codebox
      entries:
      - title: En savoir plus sur Codebox
        url: "/codebox-automation.html"
      - title: Utilisez Codebox pour générer du code
        url: "/use-codebox.html"
    - title: Utilisez CloudShell
      url: "/use-cloudshell.html"
    - title: Supprimer les informations d'identification
      url: "/manage-credentials.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/support-registration.html"
    - title: Obtenez de l'aide
      url: "/get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory
  repo: workload-family
