---
sidebar: sidebar 
permalink: well-architected-workloads.html 
keywords: well-architected, best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: 'Workload Factory analyse les configurations de charge de travail en termes de fiabilité, de sécurité, d"excellence opérationnelle, d"optimisation des coûts et d"efficacité des performances, et fournit des informations et des recommandations pour vous aider à atteindre l"excellence opérationnelle.' 
---
= Créez et exploitez des charges de travail bien architecturées avec NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory, la suite de gestion NetApp pour Amazon FSx for NetApp ONTAP, vous aide à maintenir et exploiter des configurations de charges de travail fiables, sécurisées, efficaces et économiques, conformes au AWS Well-Architected Framework. Workload Factory fournit une analyse quotidienne de vos charges de travail, des recommandations et des corrections automatiques pour promouvoir le bon fonctionnement des charges de travail. En automatisant ce processus, Workload Factory minimise les erreurs humaines et assure la cohérence dans la gestion des charges de travail.



== Comment ça marche

Workload Factory analyse vos charges de travail exécutées sur les déploiements de systèmes de fichiers Amazon FSx for NetApp ONTAP quotidiennement. L'analyse fournit un état bien architecturé, des informations et des recommandations.

Une fois l'analyse quotidienne terminée, les configurations apparaissent comme « optimisées » ou « non optimisées » dans le tableau de bord Well-architected pour le déploiement. Vous trouverez le score d'optimisation total, les problèmes de configuration par catégorie, ainsi qu'une liste des problèmes de configuration et des recommandations. Vous pouvez consulter les recommandations relatives aux problèmes de configuration. Certains problèmes peuvent être résolus automatiquement par Workload Factory, tandis que d'autres nécessitent une intervention manuelle. Dans ce cas, Workload Factory fournit des instructions détaillées pour vous aider à mettre en œuvre les modifications recommandées.

Vous pouvez ignorer l'analyse des configurations qui ne s'appliquent pas à vos environnements. Cela évite les alertes inutiles et des résultats d'optimisation inexacts. Lorsque vous ignorez une analyse de configuration spécifique, Workload Factory n'inclut pas la configuration dans le score d'optimisation total.



== Pourquoi c'est important

Workload Factory applique les meilleures pratiques aux environnements de stockage, de base de données et VMware de grande envergure en combinant une évaluation continue avec des recommandations et des corrections. Les correctifs automatisés appliqués dans la console Workload Factory réduisent les erreurs humaines, garantissent une gestion uniforme et préservent les performances et la fiabilité de vos infrastructures de charges de travail.



== Commencez à utiliser Workload Factory pour détecter et corriger les erreurs de configuration des charges de travail

Pour commencer à utiliser Workload Factory, inscrivez-vous, ajoutez des identifiants et établissez une connectivité pour gérer les ressources AWS et optimiser les charges de travail à l'aide d'Amazon FSx for NetApp ONTAP.

link:https://docs.netapp.com/us-en/workload-setup-admin/quick-start.html["Démarrage rapide"]



== Informations connexes

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Mettre en œuvre une architecture FSx bien conçue pour les systèmes de fichiers ONTAP"^]
* link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Mettre en œuvre des charges de travail de base de données bien architecturées"^]
* link:https://docs.netapp.com/us-en/workload-vmware/view-evs-well-architected.html["Mettre en œuvre des configurations EVS bien architecturées"^]

