---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: 'Découvrez les nouveautés des fonctionnalités d"administration de Workload Factory : informations d"identification du fournisseur cloud, améliorations de Codebox et bien plus encore.' 
---
= Quoi de neuf
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés des fonctionnalités d'administration de Workload Factory : informations d'identification du fournisseur cloud, améliorations de Codebox et bien plus encore.



== 4 août 2024



=== Prise en charge de Terraform

Terraform est pris en charge pour le déploiement du système de fichiers Amazon FSX pour NetApp ONTAP et la création de machines virtuelles de stockage. Le guide d'installation et d'administration contient maintenant des instructions sur l'utilisation de Terraform à partir de la Codebox.

link:use-codebox.html["Utiliser Terraform à partir de Codebox"]



== 7 juillet 2024



=== Version initiale de Workload Factory

BlueXP Workload Factory pour AWS est une plateforme puissante de gestion du cycle de vie conçue pour vous aider à optimiser vos workloads à l'aide des systèmes de fichiers Amazon FSX pour NetApp ONTAP. Parmi les charges de travail pouvant être rationalisées à l'aide de Workload Factory et FSX pour ONTAP figurent les bases de données, les migrations VMware vers VMware Cloud sur AWS, les chatbots d'IA, etc.
